# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paon', models.CharField(max_length=100, null=True)),
                ('saon', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(db_index=True, max_length=10, null=True)),
                ('town_or_city', models.CharField(db_index=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('county', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True)),
                ('type', models.CharField(choices=[('D', 'Detached'), ('S', 'Semi-Detached'), ('T', 'Terraced'), ('F', 'Flats/Maisonettes'), ('O', 'Other')], max_length=1)),
                ('age', models.CharField(choices=[('Y', 'Newly built'), ('N', 'Established building')], max_length=1)),
                ('duration', models.CharField(choices=[('F', 'Freehold'), ('L', 'Leasehold')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, null=True)),
                ('category', models.CharField(choices=[('A', 'Standard Price Paid'), ('B', ' Additional Price Paid')], max_length=1)),
                ('transfer_date', models.DateField(null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='property_prices.Property')),
            ],
        ),
    ]
