# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
