# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_prices', '0003_auto_20160504_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property_prices.Property'),
        ),
    ]
