# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_prices', '0006_auto_20160506_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='postcode',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
