# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_prices', '0007_auto_20160507_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='town_or_city',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
